table DimChannel
	lineageTag: 6362bb42-c162-4bc0-acfa-66da9dcf3f94

	column ChannelID
		dataType: string
		lineageTag: ae10911e-2dd7-492e-9b6d-6ef97a76ce2f
		summarizeBy: none
		sourceColumn: ChannelID

		annotation SummarizationSetBy = Automatic

	column ChannelName
		dataType: string
		lineageTag: c76596fb-2f16-4f5c-8691-1ff8c4d99c5f
		summarizeBy: none
		sourceColumn: ChannelName

		annotation SummarizationSetBy = Automatic

	column ChannelType
		dataType: string
		lineageTag: eeb63d67-3008-4896-95bb-8ee3837a9d25
		summarizeBy: none
		sourceColumn: ChannelType

		annotation SummarizationSetBy = Automatic

	column PromotionSensitivity
		dataType: string
		lineageTag: 62590c2b-d21c-4fb9-9d44-617eae23e19b
		summarizeBy: none
		sourceColumn: PromotionSensitivity

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 5f06178d-2074-4e2a-b97d-96ad76c1ca82
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition DimChannel = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("D:\New Work\2. Job\Supply Chain Data Analyst\Projects\3 projects\PakFresh_FMCG_Master_Data.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DimChannel", Kind = "Sheet"]}[Data],
				  #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ChannelID", type text}, {"ChannelName", type text}, {"ChannelType", type text}, {"PromotionSensitivity", type text}, {"Description", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

